var x_r_t_nibble_delegate_8java =
[
    [ "org.xvm.runtime.template._native.collections.arrays.xRTNibbleDelegate", "d6/d5f/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1x_r_t_nibble_delegate.html", "d6/d5f/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1x_r_t_nibble_delegate" ],
    [ "org.xvm.runtime.template._native.collections.arrays.xRTNibbleDelegate.NibbleArrayHandle", "d8/d2f/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1x_r_t_nibble_delegate_1_1_nibble_array_handle.html", "d8/d2f/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1x_r_t_nibble_delegate_1_1_nibble_array_handle" ]
];