var x_r_t_view_to_bit_from_nibble_8java =
[
    [ "org.xvm.runtime.template._native.collections.arrays.xRTViewToBitFromNibble", "d5/d0f/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1x_r_t_view_to_bit_from_nibble.html", "d5/d0f/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1x_r_t_view_to_bit_from_nibble" ],
    [ "org.xvm.runtime.template._native.collections.arrays.xRTViewToBitFromNibble.ViewHandle", "d9/df1/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1x_r_t_view_to_bit_from_nibble_1_1_view_handle.html", "d9/df1/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1x_r_t_view_to_bit_from_nibble_1_1_view_handle" ]
];