var searchData=
[
  ['l_5fget_0',['L_Get',['../d8/d5d/classorg_1_1xvm_1_1asm_1_1op_1_1_l___get.html',1,'org::xvm::asm::op']]],
  ['l_5fset_1',['L_Set',['../dd/d35/classorg_1_1xvm_1_1asm_1_1op_1_1_l___set.html',1,'org::xvm::asm::op']]],
  ['label_2',['Label',['../dc/d64/classorg_1_1xvm_1_1asm_1_1op_1_1_label.html',1,'org::xvm::asm::op']]],
  ['labelable_3',['LabelAble',['../d2/d1e/interfaceorg_1_1xvm_1_1compiler_1_1ast_1_1_label_able.html',1,'org::xvm::compiler::ast']]],
  ['labeledexpression_4',['LabeledExpression',['../de/da2/classorg_1_1xvm_1_1compiler_1_1ast_1_1_labeled_expression.html',1,'org::xvm::compiler::ast']]],
  ['labeledstatement_5',['LabeledStatement',['../dc/dbc/classorg_1_1xvm_1_1compiler_1_1ast_1_1_labeled_statement.html',1,'org::xvm::compiler::ast']]],
  ['labelvar_6',['LabelVar',['../d5/d70/classorg_1_1xvm_1_1compiler_1_1ast_1_1_labeled_statement_1_1_label_var.html',1,'org::xvm::compiler::ast::LabeledStatement']]],
  ['lambdacontext_7',['LambdaContext',['../d1/da1/classorg_1_1xvm_1_1compiler_1_1ast_1_1_lambda_expression_1_1_lambda_context.html',1,'org::xvm::compiler::ast::LambdaExpression']]],
  ['lambdaexpression_8',['LambdaExpression',['../dc/dd0/classorg_1_1xvm_1_1compiler_1_1ast_1_1_lambda_expression.html',1,'org::xvm::compiler::ast']]],
  ['launcher_9',['Launcher',['../d4/dfd/classorg_1_1xvm_1_1tool_1_1_launcher.html',1,'org::xvm::tool']]],
  ['launcher_3c_20compileroptions_20_3e_10',['Launcher&lt; CompilerOptions &gt;',['../d4/dfd/classorg_1_1xvm_1_1tool_1_1_launcher.html',1,'org::xvm::tool']]],
  ['launcher_3c_20disassembleroptions_20_3e_11',['Launcher&lt; DisassemblerOptions &gt;',['../d4/dfd/classorg_1_1xvm_1_1tool_1_1_launcher.html',1,'org::xvm::tool']]],
  ['launcher_3c_20initializeroptions_20_3e_12',['Launcher&lt; InitializerOptions &gt;',['../d4/dfd/classorg_1_1xvm_1_1tool_1_1_launcher.html',1,'org::xvm::tool']]],
  ['launcher_3c_20runneroptions_20_3e_13',['Launcher&lt; RunnerOptions &gt;',['../d4/dfd/classorg_1_1xvm_1_1tool_1_1_launcher.html',1,'org::xvm::tool']]],
  ['launchererrorhandlingtest_14',['LauncherErrorHandlingTest',['../d4/d3b/classorg_1_1xvm_1_1tool_1_1_launcher_error_handling_test.html',1,'org::xvm::tool']]],
  ['launcherexception_15',['LauncherException',['../d0/d3a/classorg_1_1xvm_1_1tool_1_1_launcher_1_1_launcher_exception.html',1,'org::xvm::tool::Launcher']]],
  ['launcheroptions_16',['LauncherOptions',['../de/df4/classorg_1_1xvm_1_1tool_1_1_launcher_options.html',1,'org::xvm::tool']]],
  ['launcheroptionsbuilder_17',['LauncherOptionsBuilder',['../d5/dff/classorg_1_1xtclang_1_1plugin_1_1launchers_1_1_launcher_options_builder.html',1,'org::xtclang::plugin::launchers']]],
  ['launcheroptionsjsontest_18',['LauncherOptionsJsonTest',['../dd/dba/classorg_1_1xvm_1_1tool_1_1_launcher_options_json_test.html',1,'org::xvm::tool']]],
  ['launcherversiontest_19',['LauncherVersionTest',['../d5/d91/classorg_1_1xvm_1_1tool_1_1_launcher_version_test.html',1,'org::xvm::tool']]],
  ['lazy_20',['Lazy',['../de/dd9/classorg_1_1xvm_1_1util_1_1_lazy.html',1,'org::xvm::util']]],
  ['lazyhandle_21',['LazyHandle',['../dd/d0f/classorg_1_1xvm_1_1runtime_1_1template_1_1annotations_1_1x_lazy_1_1_lazy_handle.html',1,'org::xvm::runtime::template::annotations::xLazy']]],
  ['lazytest_22',['LazyTest',['../d6/d4d/classorg_1_1xvm_1_1util_1_1_lazy_test.html',1,'org::xvm::util']]],
  ['lesser_23',['Lesser',['../dc/df9/classorg_1_1xtclang_1_1ecstasy_1_1_ordered_1_1_lesser.html',1,'org::xtclang::ecstasy::Ordered']]],
  ['lexer_24',['Lexer',['../d3/d58/classorg_1_1xvm_1_1compiler_1_1_lexer.html',1,'org::xvm::compiler']]],
  ['lexertest_25',['LexerTest',['../df/db7/classorg_1_1xvm_1_1compiler_1_1_lexer_test.html',1,'org::xvm::compiler']]],
  ['limitedhistory_26',['LimitedHistory',['../db/d1c/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1io_1_1x_terminal_console_1_1_limited_history.html',1,'org::xvm::runtime::template::_native::io::xTerminalConsole']]],
  ['linkedrepository_27',['LinkedRepository',['../dd/d11/classorg_1_1xvm_1_1asm_1_1_linked_repository.html',1,'org::xvm::asm']]],
  ['linker_28',['Linker',['../df/dab/classorg_1_1xvm_1_1javajit_1_1_linker.html',1,'org::xvm::javajit']]],
  ['linkercontext_29',['LinkerContext',['../dc/dd3/interfaceorg_1_1xvm_1_1asm_1_1_linker_context.html',1,'org::xvm::asm']]],
  ['listexprast_30',['ListExprAST',['../d3/d07/classorg_1_1xvm_1_1asm_1_1ast_1_1_list_expr_a_s_t.html',1,'org::xvm::asm::ast']]],
  ['listexpression_31',['ListExpression',['../d0/d65/classorg_1_1xvm_1_1compiler_1_1ast_1_1_list_expression.html',1,'org::xvm::compiler::ast']]],
  ['listmap_32',['ListMap',['../d6/d23/classorg_1_1xvm_1_1util_1_1_list_map.html',1,'org::xvm::util']]],
  ['listmap_3c_20file_2c_20org_3a_3axvm_3a_3atool_3a_3amoduleinfo_3a_3afilenode_20_3e_33',['ListMap&lt; File, org::xvm::tool::ModuleInfo::FileNode &gt;',['../d6/d23/classorg_1_1xvm_1_1util_1_1_list_map.html',1,'org::xvm::util']]],
  ['listmap_3c_20org_3a_3axvm_3a_3aasm_3a_3aconstant_2c_20long_20_3e_34',['ListMap&lt; org::xvm::asm::Constant, Long &gt;',['../d6/d23/classorg_1_1xvm_1_1util_1_1_list_map.html',1,'org::xvm::util']]],
  ['listmap_3c_20org_3a_3axvm_3a_3aasm_3a_3aconstants_3a_3aformalconstant_2c_20org_3a_3axvm_3a_3aasm_3a_3aconstants_3a_3atypeconstant_20_3e_35',['ListMap&lt; org::xvm::asm::constants::FormalConstant, org::xvm::asm::constants::TypeConstant &gt;',['../d6/d23/classorg_1_1xvm_1_1util_1_1_list_map.html',1,'org::xvm::util']]],
  ['listmap_3c_20org_3a_3axvm_3a_3aasm_3a_3aconstants_3a_3aidentityconstant_2c_20org_3a_3axvm_3a_3aasm_3a_3aconstants_3a_3atypeconstant_3a_3aorigin_20_3e_36',['ListMap&lt; org::xvm::asm::constants::IdentityConstant, org::xvm::asm::constants::TypeConstant::Origin &gt;',['../d6/d23/classorg_1_1xvm_1_1util_1_1_list_map.html',1,'org::xvm::util']]],
  ['listmap_3c_20org_3a_3axvm_3a_3aasm_3a_3aconstants_3a_3astringconstant_2c_20org_3a_3axvm_3a_3aasm_3a_3aconstants_3a_3atypeconstant_20_3e_37',['ListMap&lt; org::xvm::asm::constants::StringConstant, org::xvm::asm::constants::TypeConstant &gt;',['../d6/d23/classorg_1_1xvm_1_1util_1_1_list_map.html',1,'org::xvm::util']]],
  ['listmap_3c_20org_3a_3axvm_3a_3aasm_3a_3aop_3a_3alabel_2c_20cookietype_20_3e_38',['ListMap&lt; org::xvm::asm::op::Label, CookieType &gt;',['../d6/d23/classorg_1_1xvm_1_1util_1_1_list_map.html',1,'org::xvm::util']]],
  ['listmap_3c_20string_2c_20org_3a_3axvm_3a_3aasm_3a_3aconstants_3a_3achildinfo_20_3e_39',['ListMap&lt; String, org::xvm::asm::constants::ChildInfo &gt;',['../d6/d23/classorg_1_1xvm_1_1util_1_1_list_map.html',1,'org::xvm::util']]],
  ['listset_40',['ListSet',['../df/dcf/classorg_1_1xvm_1_1util_1_1_list_set.html',1,'org::xvm::util']]],
  ['listset_3c_20org_3a_3axvm_3a_3aasm_3a_3aconstant_20_3e_41',['ListSet&lt; org::xvm::asm::Constant &gt;',['../df/dcf/classorg_1_1xvm_1_1util_1_1_list_set.html',1,'org::xvm::util']]],
  ['listset_3c_20org_3a_3axvm_3a_3aruntime_3a_3atemplate_3a_3a_5fnative_3a_3atemporal_3a_3axnanostimer_3a_3atimerhandle_3a_3aalarm_20_3e_42',['ListSet&lt; org::xvm::runtime::template::_native::temporal::xNanosTimer::TimerHandle::Alarm &gt;',['../df/dcf/classorg_1_1xvm_1_1util_1_1_list_set.html',1,'org::xvm::util']]],
  ['literalconstant_43',['LiteralConstant',['../d4/d41/classorg_1_1xvm_1_1asm_1_1constants_1_1_literal_constant.html',1,'org::xvm::asm::constants']]],
  ['literalexpression_44',['LiteralExpression',['../d8/de3/classorg_1_1xvm_1_1compiler_1_1ast_1_1_literal_expression.html',1,'org::xvm::compiler::ast']]],
  ['longarrayhandle_45',['LongArrayHandle',['../d0/d9c/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1_long_based_delegate_1_1_long_array_handle.html',1,'org::xvm::runtime::template::_native::collections::arrays::LongBasedDelegate']]],
  ['longarrayobjectmanager_46',['LongArrayObjectManager',['../da/def/classorg_1_1xvm_1_1runtime_1_1gc_1_1_long_array_object_manager.html',1,'org::xvm::runtime::gc']]],
  ['longbasedbitview_47',['LongBasedBitView',['../dc/de4/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1_long_based_bit_view.html',1,'org::xvm::runtime::template::_native::collections::arrays']]],
  ['longbaseddelegate_48',['LongBasedDelegate',['../d6/dff/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1_long_based_delegate.html',1,'org::xvm::runtime::template::_native::collections::arrays']]],
  ['longdelegate_49',['LongDelegate',['../d1/d4b/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1_long_delegate.html',1,'org::xvm::runtime::template::_native::collections::arrays']]],
  ['longlist_50',['LongList',['../de/dd8/classorg_1_1xvm_1_1util_1_1_long_list.html',1,'org::xvm::util']]],
  ['longlong_51',['LongLong',['../d2/d24/classorg_1_1xvm_1_1runtime_1_1template_1_1numbers_1_1_long_long.html',1,'org::xvm::runtime::template::numbers']]],
  ['longlongdelegate_52',['LongLongDelegate',['../dd/d90/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1_long_long_delegate.html',1,'org::xvm::runtime::template::_native::collections::arrays']]],
  ['longlonghandle_53',['LongLongHandle',['../df/d9e/classorg_1_1xvm_1_1runtime_1_1template_1_1numbers_1_1_base_int128_1_1_long_long_handle.html',1,'org::xvm::runtime::template::numbers::BaseInt128']]],
  ['longmuterator_54',['LongMuterator',['../d4/d58/interfaceorg_1_1xvm_1_1util_1_1_long_muterator.html',1,'org::xvm::util']]],
  ['loop_55',['Loop',['../da/d74/classorg_1_1xvm_1_1asm_1_1op_1_1_loop.html',1,'org::xvm::asm::op']]],
  ['loopend_56',['LoopEnd',['../d5/dff/classorg_1_1xvm_1_1asm_1_1op_1_1_loop_end.html',1,'org::xvm::asm::op']]],
  ['loopingcontext_57',['LoopingContext',['../de/d01/classorg_1_1xvm_1_1compiler_1_1ast_1_1_context_1_1_looping_context.html',1,'org::xvm::compiler::ast::Context']]],
  ['loopstmtast_58',['LoopStmtAST',['../d8/d98/classorg_1_1xvm_1_1asm_1_1ast_1_1_loop_stmt_a_s_t.html',1,'org::xvm::asm::ast']]],
  ['lvaluecontext_59',['LValueContext',['../d9/d1e/classorg_1_1xvm_1_1compiler_1_1ast_1_1_assignment_statement_1_1_l_value_context.html',1,'org::xvm::compiler::ast::AssignmentStatement']]]
];
