var x_r_t_string_delegate_8java =
[
    [ "org.xvm.runtime.template._native.collections.arrays.xRTStringDelegate", "da/d57/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1x_r_t_string_delegate.html", "da/d57/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1x_r_t_string_delegate" ],
    [ "org.xvm.runtime.template._native.collections.arrays.xRTStringDelegate.StringArrayHandle", "d9/d3f/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1x_r_t_string_delegate_1_1_string_array_handle.html", "d9/d3f/classorg_1_1xvm_1_1runtime_1_1template_1_1__native_1_1collections_1_1arrays_1_1x_r_t_string_delegate_1_1_string_array_handle" ]
];